// بيانات المنتجات
const products = [
    {
        id: 1,
        name: "معالج Intel Core i9-13900K",
        category: "processors",
        price: 2499,
        oldPrice: 2799,
        discount: true,
        used: false,
        rating: 4.8,
        image: "https://via.placeholder.com/300x200?text=Intel+i9",
        description: "معالج قوي للألعاب والمهام الثقيلة بسرعة تصل إلى 5.8 جيجاهرتز",
        stock: 15,
        date: "2023-10-15"
    },
    {
        id: 2,
        name: "كرت شاشة NVIDIA RTX 4090",
        category: "gpus",
        price: 6999,
        oldPrice: 0,
        discount: false,
        used: false,
        rating: 4.9,
        image: "https://via.placeholder.com/300x200?text=RTX+4090",
        description: "أقوى كرت شاشة للألعاب والتصميم ثلاثي الأبعاد",
        stock: 8,
        date: "2023-09-20"
    },
    {
        id: 3,
        name: "لوحة أم ASUS ROG Maximus Z790",
        category: "motherboards",
        price: 1899,
        oldPrice: 1999,
        discount: true,
        used: false,
        rating: 4.7,
        image: "https://via.placeholder.com/300x200?text=ASUS+Z790",
        description: "لوحة أم مميزة لدعم أحدث معالجات إنتل",
        stock: 12,
        date: "2023-08-05"
    },
    {
        id: 4,
        name: "ذاكرة RAM Corsair 32GB DDR5",
        category: "ram",
        price: 899,
        oldPrice: 0,
        discount: false,
        used: true,
        rating: 4.5,
        image: "https://via.placeholder.com/300x200?text=Corsair+RAM",
        description: "ذاكرة عالية الأداء بسرعة 5600MHz",
        stock: 20,
        date: "2023-07-12"
    },
    {
        id: 5,
        name: "SSD Samsung 980 Pro 1TB",
        category: "storage",
        price: 599,
        oldPrice: 699,
        discount: true,
        used: false,
        rating: 4.8,
        image: "https://via.placeholder.com/300x200?text=Samsung+SSD",
        description: "وحدة تخزين سريعة بسرعة قراءة تصل إلى 7000MB/s",
        stock: 25,
        date: "2023-06-18"
    },
    {
        id: 6,
        name: "شاشة LG UltraGear 27 بوصة",
        category: "monitors",
        price: 2199,
        oldPrice: 0,
        discount: false,
        used: false,
        rating: 4.6,
        image: "https://via.placeholder.com/300x200?text=LG+Monitor",
        description: "شاشة ألعاب بدقة QHD ومعدل تحديث 144Hz",
        stock: 10,
        date: "2023-05-22"
    },
    {
        id: 7,
        name: "لوحة مفاتيح ميكانيكية Razer BlackWidow",
        category: "accessories",
        price: 499,
        oldPrice: 599,
        discount: true,
        used: true,
        rating: 4.4,
        image: "https://via.placeholder.com/300x200?text=Razer+Keyboard",
        description: "لوحة مفاتيح ميكانيكية بمفاتيح خضراء",
        stock: 18,
        date: "2023-04-30"
    },
    {
        id: 8,
        name: "ماوس لاسلكي Logitech MX Master 3",
        category: "accessories",
        price: 399,
        oldPrice: 0,
        discount: false,
        used: false,
        rating: 4.7,
        image: "https://via.placeholder.com/300x200?text=Logitech+Mouse",
        description: "ماوس لاسلكي متقدم للمحترفين",
        stock: 14,
        date: "2023-03-15"
    },
    {
        id: 9,
        name: "سماعات رأس SteelSeries Arctis Pro",
        category: "accessories",
        price: 899,
        oldPrice: 999,
        discount: true,
        used: false,
        rating: 4.6,
        image: "https://via.placeholder.com/300x200?text=SteelSeries+Headset",
        description: "سماعات ألعاب عالية الجودة مع صوت Hi-Res",
        stock: 7,
        date: "2023-02-10"
    },
    {
        id: 10,
        name: "كرت شاشة مستعمل AMD RX 6800 XT",
        category: "gpus",
        price: 2499,
        oldPrice: 3499,
        discount: true,
        used: true,
        rating: 4.3,
        image: "https://via.placeholder.com/300x200?text=AMD+GPU",
        description: "كرت شاشة قوي للألعاب بحالة جيدة",
        stock: 3,
        date: "2023-01-05"
    }
];

// التصنيفات
const categories = [
    { id: "processors", name: "المعالجات" },
    { id: "gpus", name: "كروت الشاشة" },
    { id: "motherboards", name: "لوحات الأم" },
    { id: "ram", name: "الذاكرة العشوائية" },
    { id: "storage", name: "وحدات التخزين" },
    { id: "monitors", name: "الشاشات" },
    { id: "accessories", name: "ملحقات" }
];